repositories:
  source:
    repository: 'https://github.com/ArtARTs36/php-merge-request-linter'

  target:
    repository: 'https://github.com/mr-linter/site-frontend'
    token: 'env(DOCS_RETRIEVER_HTTP_TOKEN)'

copy:
  - source: 'docs/*.md'
    target:
      directory: 'docs'
      commit:
        message: 'Add docs from main repository'

merge_request:
  title: 'Update docs'
  description: 'Updated docs from main repository'
  target_branch: 'master'
  user: 'artarts36'
